/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.18
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChatSvcMessage } from './chatSvcMessage';

export class ChatSvcGetMessagesResponse {
    'messages'?: Array<ChatSvcMessage>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ChatSvcMessage>"
        }    ];

    static getAttributeTypeMap() {
        return ChatSvcGetMessagesResponse.attributeTypeMap;
    }
}

