/**
 * OpenOrch
 * A language-agnostic microservices framework for building AI applications.
 *
 * The version of the OpenAPI document: 0.3.0-rc.20
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataSvcObject } from './dataSvcObject';
import { DatastoreFilter } from './datastoreFilter';

export class DataSvcUpdateObjectRequest {
    'filters'?: Array<DatastoreFilter>;
    'object'?: DataSvcObject;
    'table'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<DatastoreFilter>"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "DataSvcObject"
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataSvcUpdateObjectRequest.attributeTypeMap;
    }
}

