/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.18
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FileSvcUpload } from './fileSvcUpload';

export class FileSvcListUploadsResponse {
    'uploads'?: Array<FileSvcUpload>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uploads",
            "baseName": "uploads",
            "type": "Array<FileSvcUpload>"
        }    ];

    static getAttributeTypeMap() {
        return FileSvcListUploadsResponse.attributeTypeMap;
    }
}

