/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.16
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelSvcContainer } from './modelSvcContainer';

export class ModelSvcArchitectures {
    'cuda'?: ModelSvcContainer;
    '_default'?: ModelSvcContainer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cuda",
            "baseName": "cuda",
            "type": "ModelSvcContainer"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "ModelSvcContainer"
        }    ];

    static getAttributeTypeMap() {
        return ModelSvcArchitectures.attributeTypeMap;
    }
}

