/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.14
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelSvcArchitectures } from './modelSvcArchitectures';
import { OpenapiPromptSvcPromptType } from './openapiPromptSvcPromptType';

export class ModelSvcPlatform {
    'architectures'?: ModelSvcArchitectures;
    'id'?: string;
    'name'?: string;
    /**
    * Types is a list of prompt types that the AI engine supports.
    */
    'types'?: Array<OpenapiPromptSvcPromptType>;
    'version'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "architectures",
            "baseName": "architectures",
            "type": "ModelSvcArchitectures"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "Array<OpenapiPromptSvcPromptType>"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ModelSvcPlatform.attributeTypeMap;
    }
}

