/**
 * OpenOrch
 * A language-agnostic microservices framework for AI applications.
 *
 * The version of the OpenAPI document: 0.3.0-rc.19
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelSvcCudaParameters } from './modelSvcCudaParameters';
import { ModelSvcDefaultParameters } from './modelSvcDefaultParameters';

export class ModelSvcArchitectures {
    'cuda'?: ModelSvcCudaParameters;
    '_default'?: ModelSvcDefaultParameters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cuda",
            "baseName": "cuda",
            "type": "ModelSvcCudaParameters"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "ModelSvcDefaultParameters"
        }    ];

    static getAttributeTypeMap() {
        return ModelSvcArchitectures.attributeTypeMap;
    }
}

