/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RegistrySvcInstanceStatus } from './registrySvcInstanceStatus';

export class RegistrySvcInstance {
    /**
    * The ID of the deployment that this instance is an instance of.
    */
    'deploymentId': string;
    /**
    * Details
    */
    'details'?: string;
    /**
    * Host of the instance address. Required if URL is not provided
    */
    'host'?: string;
    /**
    * Required: ID of the instance
    */
    'id': string;
    /**
    * IP of the instance address. Optional: to register by IP instead of host
    */
    'ip'?: string;
    /**
    * Last time the instance gave a sign of life
    */
    'lastHeartbeat'?: string;
    /**
    * URL of the Singulatron daemon
    */
    'nodeUrl'?: string;
    /**
    * Path of the instance address. Optional (e.g., \"/api\")
    */
    'path'?: string;
    /**
    * Port of the instance address. Required if URL is not provided
    */
    'port'?: number;
    /**
    * Scheme of the instance address. Required if URL is not provided.
    */
    'scheme'?: string;
    /**
    * Status
    */
    'status': RegistrySvcInstanceStatus;
    /**
    * Full address URL of the instance.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deploymentId",
            "baseName": "deploymentId",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string"
        },
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "lastHeartbeat",
            "baseName": "lastHeartbeat",
            "type": "string"
        },
        {
            "name": "nodeUrl",
            "baseName": "nodeUrl",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RegistrySvcInstanceStatus"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegistrySvcInstance.attributeTypeMap;
    }
}

export namespace RegistrySvcInstance {
}
