# This yaml file builds the current code in this repo.
# For production use the docker-compose.yaml found at ./docs-source/docs/start/docker-compose.yaml
# or search for "Docker Compose" here https://superplatform.ai/
version: "3.8"

volumes:
  singulatron-data:
    name: singulatron-data
    driver: local

services:
  singulatron-frontend:
    build:
      context: ./desktop
      dockerfile: ./docker/Dockerfile
    ports:
      - "3901:80"
    environment:
      # The `BACKEND_ADDRESS` must be accessible from the browser.
      # It is not an internal address, it's the address the browser will make API requests to.
      - BACKEND_ADDRESS=http://127.0.0.1:58231

  singulatron-backend:
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    ports:
      - "58231:58231"
    volumes:
      # We mount the docker socket so the backend can start containers
      - /var/run/docker.sock:/var/run/docker.sock
      # We mount a volume so data will be persisted
      - singulatron-data:/root/.singulatron
    # environment:
      # GPU Acceleration for NVIDIA GPUs
      # Uncomment this envar for NVIDIA GPUs.
      #
      # - SINGULATRON_GPU_PLATFORM=cuda
