/*
OpenOrch

On-premise AI platform and microservices ecosystem.

API version: 0.3.0-rc.9
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileSvcDownloadDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSvcDownloadDetails{}

// FileSvcDownloadDetails struct for FileSvcDownloadDetails
type FileSvcDownloadDetails struct {
	Cancelled *bool `json:"cancelled,omitempty"`
	Dir *string `json:"dir,omitempty"`
	DownloadedBytes *int64 `json:"downloadedBytes,omitempty"`
	Error *string `json:"error,omitempty"`
	FileName *string `json:"fileName,omitempty"`
	FilePath *string `json:"filePath,omitempty"`
	FullFileSize *int64 `json:"fullFileSize,omitempty"`
	Id *string `json:"id,omitempty"`
	Paused *bool `json:"paused,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Status *string `json:"status,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewFileSvcDownloadDetails instantiates a new FileSvcDownloadDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSvcDownloadDetails() *FileSvcDownloadDetails {
	this := FileSvcDownloadDetails{}
	return &this
}

// NewFileSvcDownloadDetailsWithDefaults instantiates a new FileSvcDownloadDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSvcDownloadDetailsWithDefaults() *FileSvcDownloadDetails {
	this := FileSvcDownloadDetails{}
	return &this
}

// GetCancelled returns the Cancelled field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetCancelled() bool {
	if o == nil || IsNil(o.Cancelled) {
		var ret bool
		return ret
	}
	return *o.Cancelled
}

// GetCancelledOk returns a tuple with the Cancelled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetCancelledOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancelled) {
		return nil, false
	}
	return o.Cancelled, true
}

// HasCancelled returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasCancelled() bool {
	if o != nil && !IsNil(o.Cancelled) {
		return true
	}

	return false
}

// SetCancelled gets a reference to the given bool and assigns it to the Cancelled field.
func (o *FileSvcDownloadDetails) SetCancelled(v bool) {
	o.Cancelled = &v
}

// GetDir returns the Dir field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetDir() string {
	if o == nil || IsNil(o.Dir) {
		var ret string
		return ret
	}
	return *o.Dir
}

// GetDirOk returns a tuple with the Dir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetDirOk() (*string, bool) {
	if o == nil || IsNil(o.Dir) {
		return nil, false
	}
	return o.Dir, true
}

// HasDir returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasDir() bool {
	if o != nil && !IsNil(o.Dir) {
		return true
	}

	return false
}

// SetDir gets a reference to the given string and assigns it to the Dir field.
func (o *FileSvcDownloadDetails) SetDir(v string) {
	o.Dir = &v
}

// GetDownloadedBytes returns the DownloadedBytes field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetDownloadedBytes() int64 {
	if o == nil || IsNil(o.DownloadedBytes) {
		var ret int64
		return ret
	}
	return *o.DownloadedBytes
}

// GetDownloadedBytesOk returns a tuple with the DownloadedBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetDownloadedBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadedBytes) {
		return nil, false
	}
	return o.DownloadedBytes, true
}

// HasDownloadedBytes returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasDownloadedBytes() bool {
	if o != nil && !IsNil(o.DownloadedBytes) {
		return true
	}

	return false
}

// SetDownloadedBytes gets a reference to the given int64 and assigns it to the DownloadedBytes field.
func (o *FileSvcDownloadDetails) SetDownloadedBytes(v int64) {
	o.DownloadedBytes = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *FileSvcDownloadDetails) SetError(v string) {
	o.Error = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *FileSvcDownloadDetails) SetFileName(v string) {
	o.FileName = &v
}

// GetFilePath returns the FilePath field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetFilePath() string {
	if o == nil || IsNil(o.FilePath) {
		var ret string
		return ret
	}
	return *o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.FilePath) {
		return nil, false
	}
	return o.FilePath, true
}

// HasFilePath returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasFilePath() bool {
	if o != nil && !IsNil(o.FilePath) {
		return true
	}

	return false
}

// SetFilePath gets a reference to the given string and assigns it to the FilePath field.
func (o *FileSvcDownloadDetails) SetFilePath(v string) {
	o.FilePath = &v
}

// GetFullFileSize returns the FullFileSize field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetFullFileSize() int64 {
	if o == nil || IsNil(o.FullFileSize) {
		var ret int64
		return ret
	}
	return *o.FullFileSize
}

// GetFullFileSizeOk returns a tuple with the FullFileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetFullFileSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.FullFileSize) {
		return nil, false
	}
	return o.FullFileSize, true
}

// HasFullFileSize returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasFullFileSize() bool {
	if o != nil && !IsNil(o.FullFileSize) {
		return true
	}

	return false
}

// SetFullFileSize gets a reference to the given int64 and assigns it to the FullFileSize field.
func (o *FileSvcDownloadDetails) SetFullFileSize(v int64) {
	o.FullFileSize = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileSvcDownloadDetails) SetId(v string) {
	o.Id = &v
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetPaused() bool {
	if o == nil || IsNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.Paused) {
		return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasPaused() bool {
	if o != nil && !IsNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *FileSvcDownloadDetails) SetPaused(v bool) {
	o.Paused = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetProgress() float32 {
	if o == nil || IsNil(o.Progress) {
		var ret float32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetProgressOk() (*float32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float32 and assigns it to the Progress field.
func (o *FileSvcDownloadDetails) SetProgress(v float32) {
	o.Progress = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FileSvcDownloadDetails) SetStatus(v string) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FileSvcDownloadDetails) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownloadDetails) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FileSvcDownloadDetails) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FileSvcDownloadDetails) SetUrl(v string) {
	o.Url = &v
}

func (o FileSvcDownloadDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSvcDownloadDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cancelled) {
		toSerialize["cancelled"] = o.Cancelled
	}
	if !IsNil(o.Dir) {
		toSerialize["dir"] = o.Dir
	}
	if !IsNil(o.DownloadedBytes) {
		toSerialize["downloadedBytes"] = o.DownloadedBytes
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.FileName) {
		toSerialize["fileName"] = o.FileName
	}
	if !IsNil(o.FilePath) {
		toSerialize["filePath"] = o.FilePath
	}
	if !IsNil(o.FullFileSize) {
		toSerialize["fullFileSize"] = o.FullFileSize
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableFileSvcDownloadDetails struct {
	value *FileSvcDownloadDetails
	isSet bool
}

func (v NullableFileSvcDownloadDetails) Get() *FileSvcDownloadDetails {
	return v.value
}

func (v *NullableFileSvcDownloadDetails) Set(val *FileSvcDownloadDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSvcDownloadDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSvcDownloadDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSvcDownloadDetails(val *FileSvcDownloadDetails) *NullableFileSvcDownloadDetails {
	return &NullableFileSvcDownloadDetails{value: val, isSet: true}
}

func (v NullableFileSvcDownloadDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSvcDownloadDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


