/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DockerSvcGetContainerSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSvcGetContainerSummaryResponse{}

// DockerSvcGetContainerSummaryResponse struct for DockerSvcGetContainerSummaryResponse
type DockerSvcGetContainerSummaryResponse struct {
	Logs *string `json:"logs,omitempty"`
	Status *string `json:"status,omitempty"`
	// DEPRECATED. Summary contains both Status and Logs.
	Summary *string `json:"summary,omitempty"`
}

// NewDockerSvcGetContainerSummaryResponse instantiates a new DockerSvcGetContainerSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSvcGetContainerSummaryResponse() *DockerSvcGetContainerSummaryResponse {
	this := DockerSvcGetContainerSummaryResponse{}
	return &this
}

// NewDockerSvcGetContainerSummaryResponseWithDefaults instantiates a new DockerSvcGetContainerSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSvcGetContainerSummaryResponseWithDefaults() *DockerSvcGetContainerSummaryResponse {
	this := DockerSvcGetContainerSummaryResponse{}
	return &this
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *DockerSvcGetContainerSummaryResponse) GetLogs() string {
	if o == nil || IsNil(o.Logs) {
		var ret string
		return ret
	}
	return *o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSvcGetContainerSummaryResponse) GetLogsOk() (*string, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *DockerSvcGetContainerSummaryResponse) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given string and assigns it to the Logs field.
func (o *DockerSvcGetContainerSummaryResponse) SetLogs(v string) {
	o.Logs = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DockerSvcGetContainerSummaryResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSvcGetContainerSummaryResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DockerSvcGetContainerSummaryResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DockerSvcGetContainerSummaryResponse) SetStatus(v string) {
	o.Status = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *DockerSvcGetContainerSummaryResponse) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSvcGetContainerSummaryResponse) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *DockerSvcGetContainerSummaryResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *DockerSvcGetContainerSummaryResponse) SetSummary(v string) {
	o.Summary = &v
}

func (o DockerSvcGetContainerSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSvcGetContainerSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableDockerSvcGetContainerSummaryResponse struct {
	value *DockerSvcGetContainerSummaryResponse
	isSet bool
}

func (v NullableDockerSvcGetContainerSummaryResponse) Get() *DockerSvcGetContainerSummaryResponse {
	return v.value
}

func (v *NullableDockerSvcGetContainerSummaryResponse) Set(val *DockerSvcGetContainerSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSvcGetContainerSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSvcGetContainerSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSvcGetContainerSummaryResponse(val *DockerSvcGetContainerSummaryResponse) *NullableDockerSvcGetContainerSummaryResponse {
	return &NullableDockerSvcGetContainerSummaryResponse{value: val, isSet: true}
}

func (v NullableDockerSvcGetContainerSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSvcGetContainerSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


