/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SecretSvcReadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretSvcReadRequest{}

// SecretSvcReadRequest struct for SecretSvcReadRequest
type SecretSvcReadRequest struct {
	Key *string `json:"key,omitempty"`
}

// NewSecretSvcReadRequest instantiates a new SecretSvcReadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSvcReadRequest() *SecretSvcReadRequest {
	this := SecretSvcReadRequest{}
	return &this
}

// NewSecretSvcReadRequestWithDefaults instantiates a new SecretSvcReadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSvcReadRequestWithDefaults() *SecretSvcReadRequest {
	this := SecretSvcReadRequest{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SecretSvcReadRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSvcReadRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SecretSvcReadRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SecretSvcReadRequest) SetKey(v string) {
	o.Key = &v
}

func (o SecretSvcReadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretSvcReadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableSecretSvcReadRequest struct {
	value *SecretSvcReadRequest
	isSet bool
}

func (v NullableSecretSvcReadRequest) Get() *SecretSvcReadRequest {
	return v.value
}

func (v *NullableSecretSvcReadRequest) Set(val *SecretSvcReadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSvcReadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSvcReadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSvcReadRequest(val *SecretSvcReadRequest) *NullableSecretSvcReadRequest {
	return &NullableSecretSvcReadRequest{value: val, isSet: true}
}

func (v NullableSecretSvcReadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSvcReadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


