/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SecretSvcWriteSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretSvcWriteSecretRequest{}

// SecretSvcWriteSecretRequest struct for SecretSvcWriteSecretRequest
type SecretSvcWriteSecretRequest struct {
	Secret *SecretSvcSecret `json:"secret,omitempty"`
}

// NewSecretSvcWriteSecretRequest instantiates a new SecretSvcWriteSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSvcWriteSecretRequest() *SecretSvcWriteSecretRequest {
	this := SecretSvcWriteSecretRequest{}
	return &this
}

// NewSecretSvcWriteSecretRequestWithDefaults instantiates a new SecretSvcWriteSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSvcWriteSecretRequestWithDefaults() *SecretSvcWriteSecretRequest {
	this := SecretSvcWriteSecretRequest{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SecretSvcWriteSecretRequest) GetSecret() SecretSvcSecret {
	if o == nil || IsNil(o.Secret) {
		var ret SecretSvcSecret
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSvcWriteSecretRequest) GetSecretOk() (*SecretSvcSecret, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SecretSvcWriteSecretRequest) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given SecretSvcSecret and assigns it to the Secret field.
func (o *SecretSvcWriteSecretRequest) SetSecret(v SecretSvcSecret) {
	o.Secret = &v
}

func (o SecretSvcWriteSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretSvcWriteSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableSecretSvcWriteSecretRequest struct {
	value *SecretSvcWriteSecretRequest
	isSet bool
}

func (v NullableSecretSvcWriteSecretRequest) Get() *SecretSvcWriteSecretRequest {
	return v.value
}

func (v *NullableSecretSvcWriteSecretRequest) Set(val *SecretSvcWriteSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSvcWriteSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSvcWriteSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSvcWriteSecretRequest(val *SecretSvcWriteSecretRequest) *NullableSecretSvcWriteSecretRequest {
	return &NullableSecretSvcWriteSecretRequest{value: val, isSet: true}
}

func (v NullableSecretSvcWriteSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSvcWriteSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


