/*
OpenOrch

On-premise AI platform and microservices ecosystem.

API version: 0.3.0-rc.7
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SecretSvcReadSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretSvcReadSecretsResponse{}

// SecretSvcReadSecretsResponse struct for SecretSvcReadSecretsResponse
type SecretSvcReadSecretsResponse struct {
	Secrets []SecretSvcSecret `json:"secrets,omitempty"`
}

// NewSecretSvcReadSecretsResponse instantiates a new SecretSvcReadSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSvcReadSecretsResponse() *SecretSvcReadSecretsResponse {
	this := SecretSvcReadSecretsResponse{}
	return &this
}

// NewSecretSvcReadSecretsResponseWithDefaults instantiates a new SecretSvcReadSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSvcReadSecretsResponseWithDefaults() *SecretSvcReadSecretsResponse {
	this := SecretSvcReadSecretsResponse{}
	return &this
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *SecretSvcReadSecretsResponse) GetSecrets() []SecretSvcSecret {
	if o == nil || IsNil(o.Secrets) {
		var ret []SecretSvcSecret
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSvcReadSecretsResponse) GetSecretsOk() ([]SecretSvcSecret, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *SecretSvcReadSecretsResponse) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []SecretSvcSecret and assigns it to the Secrets field.
func (o *SecretSvcReadSecretsResponse) SetSecrets(v []SecretSvcSecret) {
	o.Secrets = v
}

func (o SecretSvcReadSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretSvcReadSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

type NullableSecretSvcReadSecretsResponse struct {
	value *SecretSvcReadSecretsResponse
	isSet bool
}

func (v NullableSecretSvcReadSecretsResponse) Get() *SecretSvcReadSecretsResponse {
	return v.value
}

func (v *NullableSecretSvcReadSecretsResponse) Set(val *SecretSvcReadSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSvcReadSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSvcReadSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSvcReadSecretsResponse(val *SecretSvcReadSecretsResponse) *NullableSecretSvcReadSecretsResponse {
	return &NullableSecretSvcReadSecretsResponse{value: val, isSet: true}
}

func (v NullableSecretSvcReadSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSvcReadSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


