/*
OpenOrch

On-premise AI platform and microservices ecosystem.

API version: 0.3.0-rc.8
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DockerSvcRunContainerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSvcRunContainerResponse{}

// DockerSvcRunContainerResponse struct for DockerSvcRunContainerResponse
type DockerSvcRunContainerResponse struct {
	Info *DockerSvcRunInfo `json:"info,omitempty"`
}

// NewDockerSvcRunContainerResponse instantiates a new DockerSvcRunContainerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSvcRunContainerResponse() *DockerSvcRunContainerResponse {
	this := DockerSvcRunContainerResponse{}
	return &this
}

// NewDockerSvcRunContainerResponseWithDefaults instantiates a new DockerSvcRunContainerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSvcRunContainerResponseWithDefaults() *DockerSvcRunContainerResponse {
	this := DockerSvcRunContainerResponse{}
	return &this
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *DockerSvcRunContainerResponse) GetInfo() DockerSvcRunInfo {
	if o == nil || IsNil(o.Info) {
		var ret DockerSvcRunInfo
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSvcRunContainerResponse) GetInfoOk() (*DockerSvcRunInfo, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *DockerSvcRunContainerResponse) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given DockerSvcRunInfo and assigns it to the Info field.
func (o *DockerSvcRunContainerResponse) SetInfo(v DockerSvcRunInfo) {
	o.Info = &v
}

func (o DockerSvcRunContainerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSvcRunContainerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Info) {
		toSerialize["info"] = o.Info
	}
	return toSerialize, nil
}

type NullableDockerSvcRunContainerResponse struct {
	value *DockerSvcRunContainerResponse
	isSet bool
}

func (v NullableDockerSvcRunContainerResponse) Get() *DockerSvcRunContainerResponse {
	return v.value
}

func (v *NullableDockerSvcRunContainerResponse) Set(val *DockerSvcRunContainerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSvcRunContainerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSvcRunContainerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSvcRunContainerResponse(val *DockerSvcRunContainerResponse) *NullableDockerSvcRunContainerResponse {
	return &NullableDockerSvcRunContainerResponse{value: val, isSet: true}
}

func (v NullableDockerSvcRunContainerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSvcRunContainerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


