/*
OpenOrch

AI app platform. A language-agnostic, distributed platform for building microservices-based AI apps.

API version: 0.3.0-rc.14
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerSvcContainerIsRunningResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSvcContainerIsRunningResponse{}

// DockerSvcContainerIsRunningResponse struct for DockerSvcContainerIsRunningResponse
type DockerSvcContainerIsRunningResponse struct {
	IsRunning bool `json:"isRunning"`
}

type _DockerSvcContainerIsRunningResponse DockerSvcContainerIsRunningResponse

// NewDockerSvcContainerIsRunningResponse instantiates a new DockerSvcContainerIsRunningResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSvcContainerIsRunningResponse(isRunning bool) *DockerSvcContainerIsRunningResponse {
	this := DockerSvcContainerIsRunningResponse{}
	this.IsRunning = isRunning
	return &this
}

// NewDockerSvcContainerIsRunningResponseWithDefaults instantiates a new DockerSvcContainerIsRunningResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSvcContainerIsRunningResponseWithDefaults() *DockerSvcContainerIsRunningResponse {
	this := DockerSvcContainerIsRunningResponse{}
	return &this
}

// GetIsRunning returns the IsRunning field value
func (o *DockerSvcContainerIsRunningResponse) GetIsRunning() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRunning
}

// GetIsRunningOk returns a tuple with the IsRunning field value
// and a boolean to check if the value has been set.
func (o *DockerSvcContainerIsRunningResponse) GetIsRunningOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRunning, true
}

// SetIsRunning sets field value
func (o *DockerSvcContainerIsRunningResponse) SetIsRunning(v bool) {
	o.IsRunning = v
}

func (o DockerSvcContainerIsRunningResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSvcContainerIsRunningResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isRunning"] = o.IsRunning
	return toSerialize, nil
}

func (o *DockerSvcContainerIsRunningResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isRunning",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerSvcContainerIsRunningResponse := _DockerSvcContainerIsRunningResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerSvcContainerIsRunningResponse)

	if err != nil {
		return err
	}

	*o = DockerSvcContainerIsRunningResponse(varDockerSvcContainerIsRunningResponse)

	return err
}

type NullableDockerSvcContainerIsRunningResponse struct {
	value *DockerSvcContainerIsRunningResponse
	isSet bool
}

func (v NullableDockerSvcContainerIsRunningResponse) Get() *DockerSvcContainerIsRunningResponse {
	return v.value
}

func (v *NullableDockerSvcContainerIsRunningResponse) Set(val *DockerSvcContainerIsRunningResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSvcContainerIsRunningResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSvcContainerIsRunningResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSvcContainerIsRunningResponse(val *DockerSvcContainerIsRunningResponse) *NullableDockerSvcContainerIsRunningResponse {
	return &NullableDockerSvcContainerIsRunningResponse{value: val, isSet: true}
}

func (v NullableDockerSvcContainerIsRunningResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSvcContainerIsRunningResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


