/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerSvcGetDockerHostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSvcGetDockerHostResponse{}

// DockerSvcGetDockerHostResponse struct for DockerSvcGetDockerHostResponse
type DockerSvcGetDockerHostResponse struct {
	Host string `json:"host"`
}

type _DockerSvcGetDockerHostResponse DockerSvcGetDockerHostResponse

// NewDockerSvcGetDockerHostResponse instantiates a new DockerSvcGetDockerHostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSvcGetDockerHostResponse(host string) *DockerSvcGetDockerHostResponse {
	this := DockerSvcGetDockerHostResponse{}
	this.Host = host
	return &this
}

// NewDockerSvcGetDockerHostResponseWithDefaults instantiates a new DockerSvcGetDockerHostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSvcGetDockerHostResponseWithDefaults() *DockerSvcGetDockerHostResponse {
	this := DockerSvcGetDockerHostResponse{}
	return &this
}

// GetHost returns the Host field value
func (o *DockerSvcGetDockerHostResponse) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *DockerSvcGetDockerHostResponse) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *DockerSvcGetDockerHostResponse) SetHost(v string) {
	o.Host = v
}

func (o DockerSvcGetDockerHostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSvcGetDockerHostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

func (o *DockerSvcGetDockerHostResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerSvcGetDockerHostResponse := _DockerSvcGetDockerHostResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerSvcGetDockerHostResponse)

	if err != nil {
		return err
	}

	*o = DockerSvcGetDockerHostResponse(varDockerSvcGetDockerHostResponse)

	return err
}

type NullableDockerSvcGetDockerHostResponse struct {
	value *DockerSvcGetDockerHostResponse
	isSet bool
}

func (v NullableDockerSvcGetDockerHostResponse) Get() *DockerSvcGetDockerHostResponse {
	return v.value
}

func (v *NullableDockerSvcGetDockerHostResponse) Set(val *DockerSvcGetDockerHostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSvcGetDockerHostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSvcGetDockerHostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSvcGetDockerHostResponse(val *DockerSvcGetDockerHostResponse) *NullableDockerSvcGetDockerHostResponse {
	return &NullableDockerSvcGetDockerHostResponse{value: val, isSet: true}
}

func (v NullableDockerSvcGetDockerHostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSvcGetDockerHostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


