/*
OpenOrch

On-premise AI platform and microservices ecosystem.

API version: 0.3.0-rc.10
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileSvcDownload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSvcDownload{}

// FileSvcDownload struct for FileSvcDownload
type FileSvcDownload struct {
	Cancelled *bool `json:"cancelled,omitempty"`
	Dir *string `json:"dir,omitempty"`
	DownloadedBytes *int64 `json:"downloadedBytes,omitempty"`
	Error *string `json:"error,omitempty"`
	FileName *string `json:"fileName,omitempty"`
	FilePath *string `json:"filePath,omitempty"`
	FullFileSize *int64 `json:"fullFileSize,omitempty"`
	Id *string `json:"id,omitempty"`
	Paused *bool `json:"paused,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Status *string `json:"status,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewFileSvcDownload instantiates a new FileSvcDownload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSvcDownload() *FileSvcDownload {
	this := FileSvcDownload{}
	return &this
}

// NewFileSvcDownloadWithDefaults instantiates a new FileSvcDownload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSvcDownloadWithDefaults() *FileSvcDownload {
	this := FileSvcDownload{}
	return &this
}

// GetCancelled returns the Cancelled field value if set, zero value otherwise.
func (o *FileSvcDownload) GetCancelled() bool {
	if o == nil || IsNil(o.Cancelled) {
		var ret bool
		return ret
	}
	return *o.Cancelled
}

// GetCancelledOk returns a tuple with the Cancelled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetCancelledOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancelled) {
		return nil, false
	}
	return o.Cancelled, true
}

// HasCancelled returns a boolean if a field has been set.
func (o *FileSvcDownload) HasCancelled() bool {
	if o != nil && !IsNil(o.Cancelled) {
		return true
	}

	return false
}

// SetCancelled gets a reference to the given bool and assigns it to the Cancelled field.
func (o *FileSvcDownload) SetCancelled(v bool) {
	o.Cancelled = &v
}

// GetDir returns the Dir field value if set, zero value otherwise.
func (o *FileSvcDownload) GetDir() string {
	if o == nil || IsNil(o.Dir) {
		var ret string
		return ret
	}
	return *o.Dir
}

// GetDirOk returns a tuple with the Dir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetDirOk() (*string, bool) {
	if o == nil || IsNil(o.Dir) {
		return nil, false
	}
	return o.Dir, true
}

// HasDir returns a boolean if a field has been set.
func (o *FileSvcDownload) HasDir() bool {
	if o != nil && !IsNil(o.Dir) {
		return true
	}

	return false
}

// SetDir gets a reference to the given string and assigns it to the Dir field.
func (o *FileSvcDownload) SetDir(v string) {
	o.Dir = &v
}

// GetDownloadedBytes returns the DownloadedBytes field value if set, zero value otherwise.
func (o *FileSvcDownload) GetDownloadedBytes() int64 {
	if o == nil || IsNil(o.DownloadedBytes) {
		var ret int64
		return ret
	}
	return *o.DownloadedBytes
}

// GetDownloadedBytesOk returns a tuple with the DownloadedBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetDownloadedBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadedBytes) {
		return nil, false
	}
	return o.DownloadedBytes, true
}

// HasDownloadedBytes returns a boolean if a field has been set.
func (o *FileSvcDownload) HasDownloadedBytes() bool {
	if o != nil && !IsNil(o.DownloadedBytes) {
		return true
	}

	return false
}

// SetDownloadedBytes gets a reference to the given int64 and assigns it to the DownloadedBytes field.
func (o *FileSvcDownload) SetDownloadedBytes(v int64) {
	o.DownloadedBytes = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *FileSvcDownload) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *FileSvcDownload) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *FileSvcDownload) SetError(v string) {
	o.Error = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *FileSvcDownload) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *FileSvcDownload) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *FileSvcDownload) SetFileName(v string) {
	o.FileName = &v
}

// GetFilePath returns the FilePath field value if set, zero value otherwise.
func (o *FileSvcDownload) GetFilePath() string {
	if o == nil || IsNil(o.FilePath) {
		var ret string
		return ret
	}
	return *o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.FilePath) {
		return nil, false
	}
	return o.FilePath, true
}

// HasFilePath returns a boolean if a field has been set.
func (o *FileSvcDownload) HasFilePath() bool {
	if o != nil && !IsNil(o.FilePath) {
		return true
	}

	return false
}

// SetFilePath gets a reference to the given string and assigns it to the FilePath field.
func (o *FileSvcDownload) SetFilePath(v string) {
	o.FilePath = &v
}

// GetFullFileSize returns the FullFileSize field value if set, zero value otherwise.
func (o *FileSvcDownload) GetFullFileSize() int64 {
	if o == nil || IsNil(o.FullFileSize) {
		var ret int64
		return ret
	}
	return *o.FullFileSize
}

// GetFullFileSizeOk returns a tuple with the FullFileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetFullFileSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.FullFileSize) {
		return nil, false
	}
	return o.FullFileSize, true
}

// HasFullFileSize returns a boolean if a field has been set.
func (o *FileSvcDownload) HasFullFileSize() bool {
	if o != nil && !IsNil(o.FullFileSize) {
		return true
	}

	return false
}

// SetFullFileSize gets a reference to the given int64 and assigns it to the FullFileSize field.
func (o *FileSvcDownload) SetFullFileSize(v int64) {
	o.FullFileSize = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileSvcDownload) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileSvcDownload) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileSvcDownload) SetId(v string) {
	o.Id = &v
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *FileSvcDownload) GetPaused() bool {
	if o == nil || IsNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.Paused) {
		return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *FileSvcDownload) HasPaused() bool {
	if o != nil && !IsNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *FileSvcDownload) SetPaused(v bool) {
	o.Paused = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *FileSvcDownload) GetProgress() float32 {
	if o == nil || IsNil(o.Progress) {
		var ret float32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetProgressOk() (*float32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *FileSvcDownload) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float32 and assigns it to the Progress field.
func (o *FileSvcDownload) SetProgress(v float32) {
	o.Progress = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FileSvcDownload) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FileSvcDownload) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FileSvcDownload) SetStatus(v string) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FileSvcDownload) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSvcDownload) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FileSvcDownload) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FileSvcDownload) SetUrl(v string) {
	o.Url = &v
}

func (o FileSvcDownload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSvcDownload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cancelled) {
		toSerialize["cancelled"] = o.Cancelled
	}
	if !IsNil(o.Dir) {
		toSerialize["dir"] = o.Dir
	}
	if !IsNil(o.DownloadedBytes) {
		toSerialize["downloadedBytes"] = o.DownloadedBytes
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.FileName) {
		toSerialize["fileName"] = o.FileName
	}
	if !IsNil(o.FilePath) {
		toSerialize["filePath"] = o.FilePath
	}
	if !IsNil(o.FullFileSize) {
		toSerialize["fullFileSize"] = o.FullFileSize
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableFileSvcDownload struct {
	value *FileSvcDownload
	isSet bool
}

func (v NullableFileSvcDownload) Get() *FileSvcDownload {
	return v.value
}

func (v *NullableFileSvcDownload) Set(val *FileSvcDownload) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSvcDownload) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSvcDownload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSvcDownload(val *FileSvcDownload) *NullableFileSvcDownload {
	return &NullableFileSvcDownload{value: val, isSet: true}
}

func (v NullableFileSvcDownload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSvcDownload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


