/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SecretSvcReadSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretSvcReadSecretResponse{}

// SecretSvcReadSecretResponse struct for SecretSvcReadSecretResponse
type SecretSvcReadSecretResponse struct {
	Exists *bool `json:"exists,omitempty"`
	Secret *SecretSvcSecret `json:"secret,omitempty"`
}

// NewSecretSvcReadSecretResponse instantiates a new SecretSvcReadSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSvcReadSecretResponse() *SecretSvcReadSecretResponse {
	this := SecretSvcReadSecretResponse{}
	return &this
}

// NewSecretSvcReadSecretResponseWithDefaults instantiates a new SecretSvcReadSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSvcReadSecretResponseWithDefaults() *SecretSvcReadSecretResponse {
	this := SecretSvcReadSecretResponse{}
	return &this
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *SecretSvcReadSecretResponse) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSvcReadSecretResponse) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *SecretSvcReadSecretResponse) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *SecretSvcReadSecretResponse) SetExists(v bool) {
	o.Exists = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SecretSvcReadSecretResponse) GetSecret() SecretSvcSecret {
	if o == nil || IsNil(o.Secret) {
		var ret SecretSvcSecret
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSvcReadSecretResponse) GetSecretOk() (*SecretSvcSecret, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SecretSvcReadSecretResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given SecretSvcSecret and assigns it to the Secret field.
func (o *SecretSvcReadSecretResponse) SetSecret(v SecretSvcSecret) {
	o.Secret = &v
}

func (o SecretSvcReadSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretSvcReadSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Exists) {
		toSerialize["exists"] = o.Exists
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableSecretSvcReadSecretResponse struct {
	value *SecretSvcReadSecretResponse
	isSet bool
}

func (v NullableSecretSvcReadSecretResponse) Get() *SecretSvcReadSecretResponse {
	return v.value
}

func (v *NullableSecretSvcReadSecretResponse) Set(val *SecretSvcReadSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSvcReadSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSvcReadSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSvcReadSecretResponse(val *SecretSvcReadSecretResponse) *NullableSecretSvcReadSecretResponse {
	return &NullableSecretSvcReadSecretResponse{value: val, isSet: true}
}

func (v NullableSecretSvcReadSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSvcReadSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


