/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.7
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigSvcModelServiceConfig
 */
export interface ConfigSvcModelServiceConfig {
    /**
     * 
     * @type {string}
     * @memberof ConfigSvcModelServiceConfig
     */
    currentModelId?: string;
}

/**
 * Check if a given object implements the ConfigSvcModelServiceConfig interface.
 */
export function instanceOfConfigSvcModelServiceConfig(value: object): value is ConfigSvcModelServiceConfig {
    return true;
}

export function ConfigSvcModelServiceConfigFromJSON(json: any): ConfigSvcModelServiceConfig {
    return ConfigSvcModelServiceConfigFromJSONTyped(json, false);
}

export function ConfigSvcModelServiceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSvcModelServiceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'currentModelId': json['currentModelId'] == null ? undefined : json['currentModelId'],
    };
}

  export function ConfigSvcModelServiceConfigToJSON(json: any): ConfigSvcModelServiceConfig {
      return ConfigSvcModelServiceConfigToJSONTyped(json, false);
  }

  export function ConfigSvcModelServiceConfigToJSONTyped(value?: ConfigSvcModelServiceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentModelId': value['currentModelId'],
    };
}

