/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * A language-agnostic microservices framework for building AI applications.
 *
 * The version of the OpenAPI document: 0.3.0-rc.25
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerSvcRunContainerOptions } from './ContainerSvcRunContainerOptions';
import {
    ContainerSvcRunContainerOptionsFromJSON,
    ContainerSvcRunContainerOptionsFromJSONTyped,
    ContainerSvcRunContainerOptionsToJSON,
    ContainerSvcRunContainerOptionsToJSONTyped,
} from './ContainerSvcRunContainerOptions';

/**
 * 
 * @export
 * @interface ContainerSvcRunContainerRequest
 */
export interface ContainerSvcRunContainerRequest {
    /**
     * HostPort is the port on the host machine that will be mapped to the container's port
     * @type {number}
     * @memberof ContainerSvcRunContainerRequest
     */
    hostPort?: number;
    /**
     * Image is the Docker image to use for the container
     * @type {string}
     * @memberof ContainerSvcRunContainerRequest
     */
    image: string;
    /**
     * Options provides additional options for launching the container
     * @type {ContainerSvcRunContainerOptions}
     * @memberof ContainerSvcRunContainerRequest
     */
    options?: ContainerSvcRunContainerOptions;
    /**
     * Port is the port number that the container will expose
     * @type {number}
     * @memberof ContainerSvcRunContainerRequest
     */
    port: number;
}

/**
 * Check if a given object implements the ContainerSvcRunContainerRequest interface.
 */
export function instanceOfContainerSvcRunContainerRequest(value: object): value is ContainerSvcRunContainerRequest {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function ContainerSvcRunContainerRequestFromJSON(json: any): ContainerSvcRunContainerRequest {
    return ContainerSvcRunContainerRequestFromJSONTyped(json, false);
}

export function ContainerSvcRunContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSvcRunContainerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hostPort': json['hostPort'] == null ? undefined : json['hostPort'],
        'image': json['image'],
        'options': json['options'] == null ? undefined : ContainerSvcRunContainerOptionsFromJSON(json['options']),
        'port': json['port'],
    };
}

export function ContainerSvcRunContainerRequestToJSON(json: any): ContainerSvcRunContainerRequest {
    return ContainerSvcRunContainerRequestToJSONTyped(json, false);
}

export function ContainerSvcRunContainerRequestToJSONTyped(value?: ContainerSvcRunContainerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostPort': value['hostPort'],
        'image': value['image'],
        'options': ContainerSvcRunContainerOptionsToJSON(value['options']),
        'port': value['port'],
    };
}

