/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.19
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerSvcRunInfo } from './ContainerSvcRunInfo';
import {
    ContainerSvcRunInfoFromJSON,
    ContainerSvcRunInfoFromJSONTyped,
    ContainerSvcRunInfoToJSON,
    ContainerSvcRunInfoToJSONTyped,
} from './ContainerSvcRunInfo';

/**
 * 
 * @export
 * @interface ContainerSvcRunContainerResponse
 */
export interface ContainerSvcRunContainerResponse {
    /**
     * 
     * @type {ContainerSvcRunInfo}
     * @memberof ContainerSvcRunContainerResponse
     */
    info?: ContainerSvcRunInfo;
}

/**
 * Check if a given object implements the ContainerSvcRunContainerResponse interface.
 */
export function instanceOfContainerSvcRunContainerResponse(value: object): value is ContainerSvcRunContainerResponse {
    return true;
}

export function ContainerSvcRunContainerResponseFromJSON(json: any): ContainerSvcRunContainerResponse {
    return ContainerSvcRunContainerResponseFromJSONTyped(json, false);
}

export function ContainerSvcRunContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSvcRunContainerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : ContainerSvcRunInfoFromJSON(json['info']),
    };
}

export function ContainerSvcRunContainerResponseToJSON(json: any): ContainerSvcRunContainerResponse {
    return ContainerSvcRunContainerResponseToJSONTyped(json, false);
}

export function ContainerSvcRunContainerResponseToJSONTyped(value?: ContainerSvcRunContainerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': ContainerSvcRunInfoToJSON(value['info']),
    };
}

