/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerSvcRunInfo
 */
export interface ContainerSvcRunInfo {
    /**
     * 
     * @type {boolean}
     * @memberof ContainerSvcRunInfo
     */
    newContainerStarted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ContainerSvcRunInfo
     */
    portNumber?: number;
}

/**
 * Check if a given object implements the ContainerSvcRunInfo interface.
 */
export function instanceOfContainerSvcRunInfo(value: object): value is ContainerSvcRunInfo {
    return true;
}

export function ContainerSvcRunInfoFromJSON(json: any): ContainerSvcRunInfo {
    return ContainerSvcRunInfoFromJSONTyped(json, false);
}

export function ContainerSvcRunInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSvcRunInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'newContainerStarted': json['newContainerStarted'] == null ? undefined : json['newContainerStarted'],
        'portNumber': json['portNumber'] == null ? undefined : json['portNumber'],
    };
}

export function ContainerSvcRunInfoToJSON(json: any): ContainerSvcRunInfo {
    return ContainerSvcRunInfoToJSONTyped(json, false);
}

export function ContainerSvcRunInfoToJSONTyped(value?: ContainerSvcRunInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newContainerStarted': value['newContainerStarted'],
        'portNumber': value['portNumber'],
    };
}

