/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerSvcGetDockerHostResponse
 */
export interface ContainerSvcGetDockerHostResponse {
    /**
     * 
     * @type {string}
     * @memberof ContainerSvcGetDockerHostResponse
     */
    host: string;
}

/**
 * Check if a given object implements the ContainerSvcGetDockerHostResponse interface.
 */
export function instanceOfContainerSvcGetDockerHostResponse(value: object): value is ContainerSvcGetDockerHostResponse {
    if (!('host' in value) || value['host'] === undefined) return false;
    return true;
}

export function ContainerSvcGetDockerHostResponseFromJSON(json: any): ContainerSvcGetDockerHostResponse {
    return ContainerSvcGetDockerHostResponseFromJSONTyped(json, false);
}

export function ContainerSvcGetDockerHostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSvcGetDockerHostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
    };
}

export function ContainerSvcGetDockerHostResponseToJSON(json: any): ContainerSvcGetDockerHostResponse {
    return ContainerSvcGetDockerHostResponseToJSONTyped(json, false);
}

export function ContainerSvcGetDockerHostResponseToJSONTyped(value?: ContainerSvcGetDockerHostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
    };
}

