/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.4
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerSvcStopContainerRequest
 */
export interface DockerSvcStopContainerRequest {
    /**
     * 
     * @type {string}
     * @memberof DockerSvcStopContainerRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DockerSvcStopContainerRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the DockerSvcStopContainerRequest interface.
 */
export function instanceOfDockerSvcStopContainerRequest(value: object): value is DockerSvcStopContainerRequest {
    return true;
}

export function DockerSvcStopContainerRequestFromJSON(json: any): DockerSvcStopContainerRequest {
    return DockerSvcStopContainerRequestFromJSONTyped(json, false);
}

export function DockerSvcStopContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerSvcStopContainerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DockerSvcStopContainerRequestToJSON(value?: DockerSvcStopContainerRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

