/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerSvcRunInfo
 */
export interface DockerSvcRunInfo {
    /**
     * 
     * @type {boolean}
     * @memberof DockerSvcRunInfo
     */
    newContainerStarted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DockerSvcRunInfo
     */
    portNumber?: number;
}

/**
 * Check if a given object implements the DockerSvcRunInfo interface.
 */
export function instanceOfDockerSvcRunInfo(value: object): value is DockerSvcRunInfo {
    return true;
}

export function DockerSvcRunInfoFromJSON(json: any): DockerSvcRunInfo {
    return DockerSvcRunInfoFromJSONTyped(json, false);
}

export function DockerSvcRunInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerSvcRunInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'newContainerStarted': json['newContainerStarted'] == null ? undefined : json['newContainerStarted'],
        'portNumber': json['portNumber'] == null ? undefined : json['portNumber'],
    };
}

export function DockerSvcRunInfoToJSON(value?: DockerSvcRunInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'newContainerStarted': value['newContainerStarted'],
        'portNumber': value['portNumber'],
    };
}

