/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.12
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerSvcGetContainerSummaryResponse
 */
export interface DockerSvcGetContainerSummaryResponse {
    /**
     * 
     * @type {string}
     * @memberof DockerSvcGetContainerSummaryResponse
     */
    logs: string;
    /**
     * 
     * @type {string}
     * @memberof DockerSvcGetContainerSummaryResponse
     */
    status: string;
    /**
     * DEPRECATED. Summary contains both Status and Logs.
     * @type {string}
     * @memberof DockerSvcGetContainerSummaryResponse
     */
    summary: string;
}

/**
 * Check if a given object implements the DockerSvcGetContainerSummaryResponse interface.
 */
export function instanceOfDockerSvcGetContainerSummaryResponse(value: object): value is DockerSvcGetContainerSummaryResponse {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function DockerSvcGetContainerSummaryResponseFromJSON(json: any): DockerSvcGetContainerSummaryResponse {
    return DockerSvcGetContainerSummaryResponseFromJSONTyped(json, false);
}

export function DockerSvcGetContainerSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerSvcGetContainerSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'],
        'status': json['status'],
        'summary': json['summary'],
    };
}

export function DockerSvcGetContainerSummaryResponseToJSON(json: any): DockerSvcGetContainerSummaryResponse {
    return DockerSvcGetContainerSummaryResponseToJSONTyped(json, false);
}

export function DockerSvcGetContainerSummaryResponseToJSONTyped(value?: DockerSvcGetContainerSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'],
        'status': value['status'],
        'summary': value['summary'],
    };
}

