/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.9
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DownloadSvcDownloadDetails } from './DownloadSvcDownloadDetails';
import {
    DownloadSvcDownloadDetailsFromJSON,
    DownloadSvcDownloadDetailsFromJSONTyped,
    DownloadSvcDownloadDetailsToJSON,
    DownloadSvcDownloadDetailsToJSONTyped,
} from './DownloadSvcDownloadDetails';

/**
 * 
 * @export
 * @interface DownloadSvcGetDownloadResponse
 */
export interface DownloadSvcGetDownloadResponse {
    /**
     * 
     * @type {DownloadSvcDownloadDetails}
     * @memberof DownloadSvcGetDownloadResponse
     */
    download?: DownloadSvcDownloadDetails;
    /**
     * 
     * @type {boolean}
     * @memberof DownloadSvcGetDownloadResponse
     */
    _exists: boolean;
}

/**
 * Check if a given object implements the DownloadSvcGetDownloadResponse interface.
 */
export function instanceOfDownloadSvcGetDownloadResponse(value: object): value is DownloadSvcGetDownloadResponse {
    if (!('_exists' in value) || value['_exists'] === undefined) return false;
    return true;
}

export function DownloadSvcGetDownloadResponseFromJSON(json: any): DownloadSvcGetDownloadResponse {
    return DownloadSvcGetDownloadResponseFromJSONTyped(json, false);
}

export function DownloadSvcGetDownloadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadSvcGetDownloadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'download': json['download'] == null ? undefined : DownloadSvcDownloadDetailsFromJSON(json['download']),
        '_exists': json['exists'],
    };
}

  export function DownloadSvcGetDownloadResponseToJSON(json: any): DownloadSvcGetDownloadResponse {
      return DownloadSvcGetDownloadResponseToJSONTyped(json, false);
  }

  export function DownloadSvcGetDownloadResponseToJSONTyped(value?: DownloadSvcGetDownloadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download': DownloadSvcDownloadDetailsToJSON(value['download']),
        'exists': value['_exists'],
    };
}

