/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.13
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DynamicSvcErrorResponse
 */
export interface DynamicSvcErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the DynamicSvcErrorResponse interface.
 */
export function instanceOfDynamicSvcErrorResponse(value: object): value is DynamicSvcErrorResponse {
    return true;
}

export function DynamicSvcErrorResponseFromJSON(json: any): DynamicSvcErrorResponse {
    return DynamicSvcErrorResponseFromJSONTyped(json, false);
}

export function DynamicSvcErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DynamicSvcErrorResponseToJSON(json: any): DynamicSvcErrorResponse {
    return DynamicSvcErrorResponseToJSONTyped(json, false);
}

export function DynamicSvcErrorResponseToJSONTyped(value?: DynamicSvcErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

