/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.17
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicSvcObject } from './DynamicSvcObject';
import {
    DynamicSvcObjectFromJSON,
    DynamicSvcObjectFromJSONTyped,
    DynamicSvcObjectToJSON,
    DynamicSvcObjectToJSONTyped,
} from './DynamicSvcObject';

/**
 * 
 * @export
 * @interface DynamicSvcUpsertObjectResponse
 */
export interface DynamicSvcUpsertObjectResponse {
    /**
     * 
     * @type {DynamicSvcObject}
     * @memberof DynamicSvcUpsertObjectResponse
     */
    object?: DynamicSvcObject;
}

/**
 * Check if a given object implements the DynamicSvcUpsertObjectResponse interface.
 */
export function instanceOfDynamicSvcUpsertObjectResponse(value: object): value is DynamicSvcUpsertObjectResponse {
    return true;
}

export function DynamicSvcUpsertObjectResponseFromJSON(json: any): DynamicSvcUpsertObjectResponse {
    return DynamicSvcUpsertObjectResponseFromJSONTyped(json, false);
}

export function DynamicSvcUpsertObjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcUpsertObjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : DynamicSvcObjectFromJSON(json['object']),
    };
}

export function DynamicSvcUpsertObjectResponseToJSON(json: any): DynamicSvcUpsertObjectResponse {
    return DynamicSvcUpsertObjectResponseToJSONTyped(json, false);
}

export function DynamicSvcUpsertObjectResponseToJSONTyped(value?: DynamicSvcUpsertObjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': DynamicSvcObjectToJSON(value['object']),
    };
}

