/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.12
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicSvcObject } from './DynamicSvcObject';
import {
    DynamicSvcObjectFromJSON,
    DynamicSvcObjectFromJSONTyped,
    DynamicSvcObjectToJSON,
    DynamicSvcObjectToJSONTyped,
} from './DynamicSvcObject';

/**
 * 
 * @export
 * @interface DynamicSvcQueryResponse
 */
export interface DynamicSvcQueryResponse {
    /**
     * 
     * @type {Array<DynamicSvcObject>}
     * @memberof DynamicSvcQueryResponse
     */
    objects?: Array<DynamicSvcObject>;
}

/**
 * Check if a given object implements the DynamicSvcQueryResponse interface.
 */
export function instanceOfDynamicSvcQueryResponse(value: object): value is DynamicSvcQueryResponse {
    return true;
}

export function DynamicSvcQueryResponseFromJSON(json: any): DynamicSvcQueryResponse {
    return DynamicSvcQueryResponseFromJSONTyped(json, false);
}

export function DynamicSvcQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'objects': json['objects'] == null ? undefined : ((json['objects'] as Array<any>).map(DynamicSvcObjectFromJSON)),
    };
}

export function DynamicSvcQueryResponseToJSON(json: any): DynamicSvcQueryResponse {
    return DynamicSvcQueryResponseToJSONTyped(json, false);
}

export function DynamicSvcQueryResponseToJSONTyped(value?: DynamicSvcQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objects': value['objects'] == null ? undefined : ((value['objects'] as Array<any>).map(DynamicSvcObjectToJSON)),
    };
}

