/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.15
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicSvcObject } from './DynamicSvcObject';
import {
    DynamicSvcObjectFromJSON,
    DynamicSvcObjectFromJSONTyped,
    DynamicSvcObjectToJSON,
    DynamicSvcObjectToJSONTyped,
} from './DynamicSvcObject';

/**
 * 
 * @export
 * @interface DynamicSvcCreateObjectResponse
 */
export interface DynamicSvcCreateObjectResponse {
    /**
     * 
     * @type {DynamicSvcObject}
     * @memberof DynamicSvcCreateObjectResponse
     */
    object?: DynamicSvcObject;
}

/**
 * Check if a given object implements the DynamicSvcCreateObjectResponse interface.
 */
export function instanceOfDynamicSvcCreateObjectResponse(value: object): value is DynamicSvcCreateObjectResponse {
    return true;
}

export function DynamicSvcCreateObjectResponseFromJSON(json: any): DynamicSvcCreateObjectResponse {
    return DynamicSvcCreateObjectResponseFromJSONTyped(json, false);
}

export function DynamicSvcCreateObjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcCreateObjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : DynamicSvcObjectFromJSON(json['object']),
    };
}

export function DynamicSvcCreateObjectResponseToJSON(json: any): DynamicSvcCreateObjectResponse {
    return DynamicSvcCreateObjectResponseToJSONTyped(json, false);
}

export function DynamicSvcCreateObjectResponseToJSONTyped(value?: DynamicSvcCreateObjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': DynamicSvcObjectToJSON(value['object']),
    };
}

