/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.13
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicSvcObjectCreateFields } from './DynamicSvcObjectCreateFields';
import {
    DynamicSvcObjectCreateFieldsFromJSON,
    DynamicSvcObjectCreateFieldsFromJSONTyped,
    DynamicSvcObjectCreateFieldsToJSON,
    DynamicSvcObjectCreateFieldsToJSONTyped,
} from './DynamicSvcObjectCreateFields';

/**
 * 
 * @export
 * @interface DynamicSvcCreateObjectRequest
 */
export interface DynamicSvcCreateObjectRequest {
    /**
     * 
     * @type {DynamicSvcObjectCreateFields}
     * @memberof DynamicSvcCreateObjectRequest
     */
    object?: DynamicSvcObjectCreateFields;
}

/**
 * Check if a given object implements the DynamicSvcCreateObjectRequest interface.
 */
export function instanceOfDynamicSvcCreateObjectRequest(value: object): value is DynamicSvcCreateObjectRequest {
    return true;
}

export function DynamicSvcCreateObjectRequestFromJSON(json: any): DynamicSvcCreateObjectRequest {
    return DynamicSvcCreateObjectRequestFromJSONTyped(json, false);
}

export function DynamicSvcCreateObjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcCreateObjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : DynamicSvcObjectCreateFieldsFromJSON(json['object']),
    };
}

export function DynamicSvcCreateObjectRequestToJSON(json: any): DynamicSvcCreateObjectRequest {
    return DynamicSvcCreateObjectRequestToJSONTyped(json, false);
}

export function DynamicSvcCreateObjectRequestToJSONTyped(value?: DynamicSvcCreateObjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': DynamicSvcObjectCreateFieldsToJSON(value['object']),
    };
}

