/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.10
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileSvcUpload
 */
export interface FileSvcUpload {
    /**
     * 
     * @type {string}
     * @memberof FileSvcUpload
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcUpload
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof FileSvcUpload
     */
    fullFileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FileSvcUpload
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcUpload
     */
    nodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcUpload
     */
    userId?: string;
}

/**
 * Check if a given object implements the FileSvcUpload interface.
 */
export function instanceOfFileSvcUpload(value: object): value is FileSvcUpload {
    return true;
}

export function FileSvcUploadFromJSON(json: any): FileSvcUpload {
    return FileSvcUploadFromJSONTyped(json, false);
}

export function FileSvcUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSvcUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'fullFileSize': json['fullFileSize'] == null ? undefined : json['fullFileSize'],
        'id': json['id'] == null ? undefined : json['id'],
        'nodeId': json['nodeId'] == null ? undefined : json['nodeId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

  export function FileSvcUploadToJSON(json: any): FileSvcUpload {
      return FileSvcUploadToJSONTyped(json, false);
  }

  export function FileSvcUploadToJSONTyped(value?: FileSvcUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fullFileSize': value['fullFileSize'],
        'id': value['id'],
        'nodeId': value['nodeId'],
        'userId': value['userId'],
    };
}

