/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.9
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileSvcDownloadDetails
 */
export interface FileSvcDownloadDetails {
    /**
     * 
     * @type {boolean}
     * @memberof FileSvcDownloadDetails
     */
    cancelled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    dir?: string;
    /**
     * 
     * @type {number}
     * @memberof FileSvcDownloadDetails
     */
    downloadedBytes?: number;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof FileSvcDownloadDetails
     */
    fullFileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileSvcDownloadDetails
     */
    paused?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FileSvcDownloadDetails
     */
    progress?: number;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadDetails
     */
    url?: string;
}

/**
 * Check if a given object implements the FileSvcDownloadDetails interface.
 */
export function instanceOfFileSvcDownloadDetails(value: object): value is FileSvcDownloadDetails {
    return true;
}

export function FileSvcDownloadDetailsFromJSON(json: any): FileSvcDownloadDetails {
    return FileSvcDownloadDetailsFromJSONTyped(json, false);
}

export function FileSvcDownloadDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSvcDownloadDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelled': json['cancelled'] == null ? undefined : json['cancelled'],
        'dir': json['dir'] == null ? undefined : json['dir'],
        'downloadedBytes': json['downloadedBytes'] == null ? undefined : json['downloadedBytes'],
        'error': json['error'] == null ? undefined : json['error'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'fullFileSize': json['fullFileSize'] == null ? undefined : json['fullFileSize'],
        'id': json['id'] == null ? undefined : json['id'],
        'paused': json['paused'] == null ? undefined : json['paused'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function FileSvcDownloadDetailsToJSON(json: any): FileSvcDownloadDetails {
      return FileSvcDownloadDetailsToJSONTyped(json, false);
  }

  export function FileSvcDownloadDetailsToJSONTyped(value?: FileSvcDownloadDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelled': value['cancelled'],
        'dir': value['dir'],
        'downloadedBytes': value['downloadedBytes'],
        'error': value['error'],
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fullFileSize': value['fullFileSize'],
        'id': value['id'],
        'paused': value['paused'],
        'progress': value['progress'],
        'status': value['status'],
        'url': value['url'],
    };
}

