/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.10
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileSvcDownloadRequest
 */
export interface FileSvcDownloadRequest {
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadRequest
     */
    folderPath?: string;
    /**
     * 
     * @type {string}
     * @memberof FileSvcDownloadRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the FileSvcDownloadRequest interface.
 */
export function instanceOfFileSvcDownloadRequest(value: object): value is FileSvcDownloadRequest {
    return true;
}

export function FileSvcDownloadRequestFromJSON(json: any): FileSvcDownloadRequest {
    return FileSvcDownloadRequestFromJSONTyped(json, false);
}

export function FileSvcDownloadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSvcDownloadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'folderPath': json['folderPath'] == null ? undefined : json['folderPath'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function FileSvcDownloadRequestToJSON(json: any): FileSvcDownloadRequest {
      return FileSvcDownloadRequestToJSONTyped(json, false);
  }

  export function FileSvcDownloadRequestToJSONTyped(value?: FileSvcDownloadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'folderPath': value['folderPath'],
        'url': value['url'],
    };
}

