/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.10
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSvcUpload } from './FileSvcUpload';
import {
    FileSvcUploadFromJSON,
    FileSvcUploadFromJSONTyped,
    FileSvcUploadToJSON,
    FileSvcUploadToJSONTyped,
} from './FileSvcUpload';

/**
 * 
 * @export
 * @interface FileSvcUploadsResponse
 */
export interface FileSvcUploadsResponse {
    /**
     * 
     * @type {Array<FileSvcUpload>}
     * @memberof FileSvcUploadsResponse
     */
    uploads?: Array<FileSvcUpload>;
}

/**
 * Check if a given object implements the FileSvcUploadsResponse interface.
 */
export function instanceOfFileSvcUploadsResponse(value: object): value is FileSvcUploadsResponse {
    return true;
}

export function FileSvcUploadsResponseFromJSON(json: any): FileSvcUploadsResponse {
    return FileSvcUploadsResponseFromJSONTyped(json, false);
}

export function FileSvcUploadsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSvcUploadsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploads': json['uploads'] == null ? undefined : ((json['uploads'] as Array<any>).map(FileSvcUploadFromJSON)),
    };
}

  export function FileSvcUploadsResponseToJSON(json: any): FileSvcUploadsResponse {
      return FileSvcUploadsResponseToJSONTyped(json, false);
  }

  export function FileSvcUploadsResponseToJSONTyped(value?: FileSvcUploadsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploads': value['uploads'] == null ? undefined : ((value['uploads'] as Array<any>).map(FileSvcUploadToJSON)),
    };
}

