/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * AI app platform. A language-agnostic, distributed platform for building microservices-based AI backends.
 *
 * The version of the OpenAPI document: 0.3.0-rc.15
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelSvcContainer } from './ModelSvcContainer';
import {
    ModelSvcContainerFromJSON,
    ModelSvcContainerFromJSONTyped,
    ModelSvcContainerToJSON,
    ModelSvcContainerToJSONTyped,
} from './ModelSvcContainer';

/**
 * 
 * @export
 * @interface ModelSvcArchitectures
 */
export interface ModelSvcArchitectures {
    /**
     * 
     * @type {ModelSvcContainer}
     * @memberof ModelSvcArchitectures
     */
    cuda?: ModelSvcContainer;
    /**
     * 
     * @type {ModelSvcContainer}
     * @memberof ModelSvcArchitectures
     */
    _default?: ModelSvcContainer;
}

/**
 * Check if a given object implements the ModelSvcArchitectures interface.
 */
export function instanceOfModelSvcArchitectures(value: object): value is ModelSvcArchitectures {
    return true;
}

export function ModelSvcArchitecturesFromJSON(json: any): ModelSvcArchitectures {
    return ModelSvcArchitecturesFromJSONTyped(json, false);
}

export function ModelSvcArchitecturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSvcArchitectures {
    if (json == null) {
        return json;
    }
    return {
        
        'cuda': json['cuda'] == null ? undefined : ModelSvcContainerFromJSON(json['cuda']),
        '_default': json['default'] == null ? undefined : ModelSvcContainerFromJSON(json['default']),
    };
}

export function ModelSvcArchitecturesToJSON(json: any): ModelSvcArchitectures {
    return ModelSvcArchitecturesToJSONTyped(json, false);
}

export function ModelSvcArchitecturesToJSONTyped(value?: ModelSvcArchitectures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cuda': ModelSvcContainerToJSON(value['cuda']),
        'default': ModelSvcContainerToJSON(value['_default']),
    };
}

