/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.14
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelSvcModel } from './ModelSvcModel';
import {
    ModelSvcModelFromJSON,
    ModelSvcModelFromJSONTyped,
    ModelSvcModelToJSON,
    ModelSvcModelToJSONTyped,
} from './ModelSvcModel';

/**
 * 
 * @export
 * @interface ModelSvcListResponse
 */
export interface ModelSvcListResponse {
    /**
     * 
     * @type {Array<ModelSvcModel>}
     * @memberof ModelSvcListResponse
     */
    models?: Array<ModelSvcModel>;
}

/**
 * Check if a given object implements the ModelSvcListResponse interface.
 */
export function instanceOfModelSvcListResponse(value: object): value is ModelSvcListResponse {
    return true;
}

export function ModelSvcListResponseFromJSON(json: any): ModelSvcListResponse {
    return ModelSvcListResponseFromJSONTyped(json, false);
}

export function ModelSvcListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSvcListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'models': json['models'] == null ? undefined : ((json['models'] as Array<any>).map(ModelSvcModelFromJSON)),
    };
}

export function ModelSvcListResponseToJSON(json: any): ModelSvcListResponse {
    return ModelSvcListResponseToJSONTyped(json, false);
}

export function ModelSvcListResponseToJSONTyped(value?: ModelSvcListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': value['models'] == null ? undefined : ((value['models'] as Array<any>).map(ModelSvcModelToJSON)),
    };
}

