/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.14
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OpenapiPromptSvcPromptType = {
    PromptTypeImageTextToText: 'Image-Text-to-Text',
    PromptTypeVisualQuestionAnswering: 'Visual Question Answering',
    PromptTypeDocumentQuestionAnswering: 'Document Question Answering',
    PromptTypeTextToImage: 'Text-to-Image',
    PromptTypeImageToImage: 'Image-to-Image',
    PromptTypeImageToVideo: 'Image-to-Video',
    PromptTypeUnconditionalImageGeneration: 'Unconditional Image Generation',
    PromptTypeTextToVideo: 'Text-to-Video',
    PromptTypeZeroShotImageClassification: 'Zero-Shot Image Classification',
    PromptTypeZeroShotObjectDetection: 'Zero-Shot Object Detection',
    PromptTypeTextTo3D: 'Text-to-3D',
    PromptTypeImageTo3D: 'Image-to-3D',
    PromptTypeImageFeatureExtraction: 'Image Feature Extraction',
    PromptTypeKeypointDetection: 'Keypoint Detection',
    PromptTypeTextToText: 'Text-to-Text',
    PromptTypeQuestionAnswering: 'Question Answering',
    PromptTypeTranslation: 'Translation',
    PromptTypeSummarization: 'Summarization',
    PromptTypeTextGeneration: 'Text Generation',
    PromptTypeFillMask: 'Fill-Mask',
    PromptTypeTextToSpeech: 'Text-to-Speech',
    PromptTypeTextToAudio: 'Text-to-Audio',
    PromptTypeAutomaticSpeechRecognition: 'Automatic Speech Recognition',
    PromptTypeAudioToAudio: 'Audio-to-Audio',
    PromptTypeAudioClassification: 'Audio Classification',
    PromptTypeReinforcementLearning: 'Reinforcement Learning',
    PromptTypeRobotics: 'Robotics',
    PromptTypeGraphMachineLearning: 'Graph Machine Learning'
} as const;
export type OpenapiPromptSvcPromptType = typeof OpenapiPromptSvcPromptType[keyof typeof OpenapiPromptSvcPromptType];


export function instanceOfOpenapiPromptSvcPromptType(value: any): boolean {
    for (const key in OpenapiPromptSvcPromptType) {
        if (Object.prototype.hasOwnProperty.call(OpenapiPromptSvcPromptType, key)) {
            if (OpenapiPromptSvcPromptType[key as keyof typeof OpenapiPromptSvcPromptType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OpenapiPromptSvcPromptTypeFromJSON(json: any): OpenapiPromptSvcPromptType {
    return OpenapiPromptSvcPromptTypeFromJSONTyped(json, false);
}

export function OpenapiPromptSvcPromptTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenapiPromptSvcPromptType {
    return json as OpenapiPromptSvcPromptType;
}

export function OpenapiPromptSvcPromptTypeToJSON(value?: OpenapiPromptSvcPromptType | null): any {
    return value as any;
}

export function OpenapiPromptSvcPromptTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OpenapiPromptSvcPromptType {
    return value as OpenapiPromptSvcPromptType;
}

