/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.13
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenapiChatSvcMessage
 */
export interface OpenapiChatSvcMessage {
    /**
     * 
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    createdAt?: string;
    /**
     * FileIds defines the file attachments the message has.
     * @type {Array<string>}
     * @memberof OpenapiChatSvcMessage
     */
    fileIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    id?: string;
    /**
     * Text content of the message eg. \"Hi, what's up?\"
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    text?: string;
    /**
     * ThreadId of the message.
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    updatedAt?: string;
    /**
     * UserId is the id of the user who wrote the message. For AI messages this field is empty.
     * @type {string}
     * @memberof OpenapiChatSvcMessage
     */
    userId?: string;
}

/**
 * Check if a given object implements the OpenapiChatSvcMessage interface.
 */
export function instanceOfOpenapiChatSvcMessage(value: object): value is OpenapiChatSvcMessage {
    return true;
}

export function OpenapiChatSvcMessageFromJSON(json: any): OpenapiChatSvcMessage {
    return OpenapiChatSvcMessageFromJSONTyped(json, false);
}

export function OpenapiChatSvcMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenapiChatSvcMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function OpenapiChatSvcMessageToJSON(json: any): OpenapiChatSvcMessage {
    return OpenapiChatSvcMessageToJSONTyped(json, false);
}

export function OpenapiChatSvcMessageToJSONTyped(value?: OpenapiChatSvcMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'fileIds': value['fileIds'],
        'id': value['id'],
        'text': value['text'],
        'threadId': value['threadId'],
        'updatedAt': value['updatedAt'],
        'userId': value['userId'],
    };
}

