/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.11
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PromptSvcStableDiffusionParameters } from './PromptSvcStableDiffusionParameters';
import {
    PromptSvcStableDiffusionParametersFromJSON,
    PromptSvcStableDiffusionParametersFromJSONTyped,
    PromptSvcStableDiffusionParametersToJSON,
    PromptSvcStableDiffusionParametersToJSONTyped,
} from './PromptSvcStableDiffusionParameters';

/**
 * 
 * @export
 * @interface PromptSvcParameters
 */
export interface PromptSvcParameters {
    /**
     * 
     * @type {PromptSvcStableDiffusionParameters}
     * @memberof PromptSvcParameters
     */
    lastRun?: PromptSvcStableDiffusionParameters;
}

/**
 * Check if a given object implements the PromptSvcParameters interface.
 */
export function instanceOfPromptSvcParameters(value: object): value is PromptSvcParameters {
    return true;
}

export function PromptSvcParametersFromJSON(json: any): PromptSvcParameters {
    return PromptSvcParametersFromJSONTyped(json, false);
}

export function PromptSvcParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptSvcParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'lastRun': json['lastRun'] == null ? undefined : PromptSvcStableDiffusionParametersFromJSON(json['lastRun']),
    };
}

export function PromptSvcParametersToJSON(json: any): PromptSvcParameters {
    return PromptSvcParametersToJSONTyped(json, false);
}

export function PromptSvcParametersToJSONTyped(value?: PromptSvcParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastRun': PromptSvcStableDiffusionParametersToJSON(value['lastRun']),
    };
}

