/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.7
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecretSvcReadSecretRequest
 */
export interface SecretSvcReadSecretRequest {
    /**
     * 
     * @type {string}
     * @memberof SecretSvcReadSecretRequest
     */
    key?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SecretSvcReadSecretRequest
     */
    keys?: Array<string>;
}

/**
 * Check if a given object implements the SecretSvcReadSecretRequest interface.
 */
export function instanceOfSecretSvcReadSecretRequest(value: object): value is SecretSvcReadSecretRequest {
    return true;
}

export function SecretSvcReadSecretRequestFromJSON(json: any): SecretSvcReadSecretRequest {
    return SecretSvcReadSecretRequestFromJSONTyped(json, false);
}

export function SecretSvcReadSecretRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSvcReadSecretRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'keys': json['keys'] == null ? undefined : json['keys'],
    };
}

  export function SecretSvcReadSecretRequestToJSON(json: any): SecretSvcReadSecretRequest {
      return SecretSvcReadSecretRequestToJSONTyped(json, false);
  }

  export function SecretSvcReadSecretRequestToJSONTyped(value?: SecretSvcReadSecretRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'keys': value['keys'],
    };
}

