/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.7
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretSvcSecret } from './SecretSvcSecret';
import {
    SecretSvcSecretFromJSON,
    SecretSvcSecretFromJSONTyped,
    SecretSvcSecretToJSON,
    SecretSvcSecretToJSONTyped,
} from './SecretSvcSecret';

/**
 * 
 * @export
 * @interface SecretSvcReadSecretResponse
 */
export interface SecretSvcReadSecretResponse {
    /**
     * 
     * @type {Array<SecretSvcSecret>}
     * @memberof SecretSvcReadSecretResponse
     */
    secrets?: Array<SecretSvcSecret>;
}

/**
 * Check if a given object implements the SecretSvcReadSecretResponse interface.
 */
export function instanceOfSecretSvcReadSecretResponse(value: object): value is SecretSvcReadSecretResponse {
    return true;
}

export function SecretSvcReadSecretResponseFromJSON(json: any): SecretSvcReadSecretResponse {
    return SecretSvcReadSecretResponseFromJSONTyped(json, false);
}

export function SecretSvcReadSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSvcReadSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'secrets': json['secrets'] == null ? undefined : ((json['secrets'] as Array<any>).map(SecretSvcSecretFromJSON)),
    };
}

  export function SecretSvcReadSecretResponseToJSON(json: any): SecretSvcReadSecretResponse {
      return SecretSvcReadSecretResponseToJSONTyped(json, false);
  }

  export function SecretSvcReadSecretResponseToJSONTyped(value?: SecretSvcReadSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secrets': value['secrets'] == null ? undefined : ((value['secrets'] as Array<any>).map(SecretSvcSecretToJSON)),
    };
}

