/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.7
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretSvcSecret } from './SecretSvcSecret';
import {
    SecretSvcSecretFromJSON,
    SecretSvcSecretFromJSONTyped,
    SecretSvcSecretToJSON,
    SecretSvcSecretToJSONTyped,
} from './SecretSvcSecret';

/**
 * 
 * @export
 * @interface SecretSvcWriteSecretsRequest
 */
export interface SecretSvcWriteSecretsRequest {
    /**
     * 
     * @type {Array<SecretSvcSecret>}
     * @memberof SecretSvcWriteSecretsRequest
     */
    secrets?: Array<SecretSvcSecret>;
}

/**
 * Check if a given object implements the SecretSvcWriteSecretsRequest interface.
 */
export function instanceOfSecretSvcWriteSecretsRequest(value: object): value is SecretSvcWriteSecretsRequest {
    return true;
}

export function SecretSvcWriteSecretsRequestFromJSON(json: any): SecretSvcWriteSecretsRequest {
    return SecretSvcWriteSecretsRequestFromJSONTyped(json, false);
}

export function SecretSvcWriteSecretsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSvcWriteSecretsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'secrets': json['secrets'] == null ? undefined : ((json['secrets'] as Array<any>).map(SecretSvcSecretFromJSON)),
    };
}

  export function SecretSvcWriteSecretsRequestToJSON(json: any): SecretSvcWriteSecretsRequest {
      return SecretSvcWriteSecretsRequestToJSONTyped(json, false);
  }

  export function SecretSvcWriteSecretsRequestToJSONTyped(value?: SecretSvcWriteSecretsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secrets': value['secrets'] == null ? undefined : ((value['secrets'] as Array<any>).map(SecretSvcSecretToJSON)),
    };
}

