/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretSvcSecret } from './SecretSvcSecret';
import {
    SecretSvcSecretFromJSON,
    SecretSvcSecretFromJSONTyped,
    SecretSvcSecretToJSON,
} from './SecretSvcSecret';

/**
 * 
 * @export
 * @interface SecretSvcReadSecretResponse
 */
export interface SecretSvcReadSecretResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SecretSvcReadSecretResponse
     */
    _exists?: boolean;
    /**
     * 
     * @type {SecretSvcSecret}
     * @memberof SecretSvcReadSecretResponse
     */
    secret?: SecretSvcSecret;
}

/**
 * Check if a given object implements the SecretSvcReadSecretResponse interface.
 */
export function instanceOfSecretSvcReadSecretResponse(value: object): value is SecretSvcReadSecretResponse {
    return true;
}

export function SecretSvcReadSecretResponseFromJSON(json: any): SecretSvcReadSecretResponse {
    return SecretSvcReadSecretResponseFromJSONTyped(json, false);
}

export function SecretSvcReadSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSvcReadSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'] == null ? undefined : json['exists'],
        'secret': json['secret'] == null ? undefined : SecretSvcSecretFromJSON(json['secret']),
    };
}

export function SecretSvcReadSecretResponseToJSON(value?: SecretSvcReadSecretResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exists': value['_exists'],
        'secret': SecretSvcSecretToJSON(value['secret']),
    };
}

