/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.11
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSvcPermission } from './UserSvcPermission';
import {
    UserSvcPermissionFromJSON,
    UserSvcPermissionFromJSONTyped,
    UserSvcPermissionToJSON,
    UserSvcPermissionToJSONTyped,
} from './UserSvcPermission';

/**
 * 
 * @export
 * @interface UserSvcUpserPermissionRequest
 */
export interface UserSvcUpserPermissionRequest {
    /**
     * 
     * @type {UserSvcPermission}
     * @memberof UserSvcUpserPermissionRequest
     */
    permission?: UserSvcPermission;
}

/**
 * Check if a given object implements the UserSvcUpserPermissionRequest interface.
 */
export function instanceOfUserSvcUpserPermissionRequest(value: object): value is UserSvcUpserPermissionRequest {
    return true;
}

export function UserSvcUpserPermissionRequestFromJSON(json: any): UserSvcUpserPermissionRequest {
    return UserSvcUpserPermissionRequestFromJSONTyped(json, false);
}

export function UserSvcUpserPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcUpserPermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': json['permission'] == null ? undefined : UserSvcPermissionFromJSON(json['permission']),
    };
}

export function UserSvcUpserPermissionRequestToJSON(json: any): UserSvcUpserPermissionRequest {
    return UserSvcUpserPermissionRequestToJSONTyped(json, false);
}

export function UserSvcUpserPermissionRequestToJSONTyped(value?: UserSvcUpserPermissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission': UserSvcPermissionToJSON(value['permission']),
    };
}

