/* tslint:disable */
/* eslint-disable */
/**
 * OpenOrch
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.3.0-rc.13
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcChangePasswordAdminRequest
 */
export interface UserSvcChangePasswordAdminRequest {
    /**
     * 
     * @type {string}
     * @memberof UserSvcChangePasswordAdminRequest
     */
    newPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcChangePasswordAdminRequest
     */
    slug?: string;
}

/**
 * Check if a given object implements the UserSvcChangePasswordAdminRequest interface.
 */
export function instanceOfUserSvcChangePasswordAdminRequest(value: object): value is UserSvcChangePasswordAdminRequest {
    return true;
}

export function UserSvcChangePasswordAdminRequestFromJSON(json: any): UserSvcChangePasswordAdminRequest {
    return UserSvcChangePasswordAdminRequestFromJSONTyped(json, false);
}

export function UserSvcChangePasswordAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcChangePasswordAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function UserSvcChangePasswordAdminRequestToJSON(json: any): UserSvcChangePasswordAdminRequest {
    return UserSvcChangePasswordAdminRequestToJSONTyped(json, false);
}

export function UserSvcChangePasswordAdminRequestToJSONTyped(value?: UserSvcChangePasswordAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newPassword': value['newPassword'],
        'slug': value['slug'],
    };
}

