name: "Backend build"
# .
on:
  push:
    paths:
      - "dapper/**"
      - "server/**"
      - ".github/workflows/backend-build-github.yaml"

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"

      - name: Install dependencies
        run: |
          cd server
          go mod tidy

      - name: Run tests
        run: |
          docker rm -f mypostgres
          docker run --name mypostgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=mydatabase -p 5432:5432 -d postgres

          # Run non dist tests with localstore backend
          go test ./... -v -tags='!dist'

          # We rerun nondist tests with an SQL backend
          SINGULATRON_DB=postgres \
            SINGULATRON_DB_DEBUG=true \
            SINGULATRON_DB_SQL_CONNECTION_STRING="postgres://postgres:mysecretpassword@localhost:5432/mydatabase?sslmode=disable" \
            go test ./... -tags='!dist'

          # Run dist test with SQL (localstore makes no sense in a dist setting)
          SINGULATRON_DB=postgres \
            SINGULATRON_DB_DEBUG=true \
            SINGULATRON_DB_SQL_CONNECTION_STRING="postgres://postgres:mysecretpassword@localhost:5432/mydatabase?sslmode=disable" \
            go test ./... -tags=dist
        working-directory: server

      - name: Test OpenAPI annotations
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          npm install @openapitools/openapi-generator-cli -g
          swag init --parseDependency
          openapi-generator-cli generate -i docs/swagger.yaml -g typescript-fetch -o ./genn
        working-directory: server
