name: "Backend container build and push to DockerHub"

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/backend-container-build-github.yaml"
      - "server/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: "singulatron-backend"

jobs:
  build-and-push:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -f ./server/docker/Dockerfile -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

          # The NVIDIA version is needed to interact with the GPUs - for example in the Node Svc
          DOCKER_BUILDKIT=1 docker build -f ./server/docker/DockerfileNvidia -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:nvidia-latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:nvidia-latest
