name: "Deploy Demo"
on:
  push:

jobs:
  index-deploy:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: ssh-keyscan -H ${{ secrets.DEMO_DOMAIN }} >> ~/.ssh/known_host

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DEMO_DOMAIN }} << 'ENDSSH'
            cd ${{ secrets.DEMO_FOLDER }}
            bash ${{ secrets.DEMO_SCRIPT }}
          ENDSSH
