name: Build Go client

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Go client
        run: |
          npm install @openapitools/openapi-generator-cli -g
          bash gen.sh

        working-directory: ./clients/go

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes detected. Failing the build."
            exit 1
          else
            echo "No changes detected."
          fi
