name: Run client-example

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Link local packages
        run: |
          bash link_local.sh
        working-directory: ./clients/js

      - name: Run
        run: |
          cp ../../../docker-compose.yaml .
          docker compose up singulatron-backend -d

          HOST="127.0.0.1"
          PORT=58231

          while ! nc -z $HOST $PORT; do
            echo "Waiting for $HOST:$PORT to come online..."
            sleep 1
          done

          sleep 2

          set -e
          (
            node ./dist/index.js
          ) || (
            echo "Node.js script failed, running docker commands for diagnostics..."
            docker ps
            docker logs singulatron-backend
            exit 1
          )
        working-directory: ./clients/js/client-example
