name: "[GH] Localtron build"
# .
on:
  push:
    paths:
      - "dapper/**"
      - "localtron/**"
      - ".github/workflows/localtron-build-github.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.4"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: Install dependencies
        run: |
          cd localtron
          go mod tidy

      - name: Run tests
        run: |
          cd localtron
          go test ./... -v
