name: "Stable Diffusion Docker build"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: false
        default: "main"

      tag:
        description: "Tag to apply to the Docker image"
        required: false
        default: "latest"

      backend:
        description: |
          Specifies the compute backend to use.  
          - This determines which hardware acceleration libraries are enabled.  
          - Options:  
            - "cuda" (for NVIDIA GPUs)  
            - "openblas" (for OpenBLAS-based CPU computations)  
            - "mkl" (for Intel MKL-based CPU computations)  
            - "default" (automatic selection)
        required: true
        default: "cuda"

      backend_version:
        description: |
          Specifies the backend version.  
          - This is typically relevant for GPU-enabled environments.  
          - Example: "12.5" for CUDA, indicating the CUDA version.
        required: false
        default: "12.1"

      cudnn_version:
        description: |
          Defines the cuDNN (CUDA Deep Neural Network) library version.  
          - This is only applicable when using CUDA-based images.  
          - Unlike the backend version, the cuDNN version does *not* appear in the final image name.
        required: false
        default: "9"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: "stable-diffusion"

jobs:
  build-and-push:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Validate Backend Selection
        run: |
          case "${{ github.event.inputs.backend }}" in
            "cuda"|"openblas"|"mkl"|"default") ;;
            *) echo "Error: Invalid backend specified"; exit 1 ;;
          esac

      - name: Set Image Tag
        run: |
          IMAGE_TAG="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.backend }}-${{ github.event.inputs.backend_version }}-${{ github.event.inputs.tag }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          cd ${{ github.event.inputs.backend }}

          DOCKER_BUILDKIT=1 docker build \
            --build-arg BACKEND_VERSION=${{ github.event.inputs.backend_version }} \
            --build-arg CUDNN_VERSION=${{ github.event.inputs.cudnn_version }} \         
            -t ${{ env.IMAGE_TAG }} .

          docker push ${{ env.IMAGE_TAG }}
        working-directory: ./server/docker/stable-diffusion
